#!/usr/bin/env python3

# pip install gitpython
import git
import os
import re
import sys
import threading
import time
import itertools
from subprocess import call
import configparser

blnDone = False
sourceBranch = 'develop'
targetBranch = 'master'

def getNextRelease(strRelease):
    x = re.findall(r"^(v\d{1,4}\.\d{1,4}\.)(\d{1,4})(\.\d{1,4})?$", strRelease)
    next = str(int(x[0][1]) + 1)
    return x[0][0] + next

def animate(var):
    global blnDone
    global sourceBranch
    global targetBranch
    if (var == 'd'):
        var = sourceBranch
    else:
        var = targetBranch
    for c in itertools.cycle(['|', '/', '-', '\\']):
        if blnDone:
            break
        sys.stdout.write('\rPush to ' + var + ' ' + c)
        sys.stdout.flush()
        time.sleep(0.1)
    sys.stdout.write('\rPush to ' + var + ' done.\n')

def runCommand(strCmd, strArgs):
    arrCmdAndArgs = []
    if strArgs != 'none':
        arrCmdAndArgs = strArgs.split()

    arrCmdAndArgs.insert(0, strCmd)
    if strCmd != 'none':
        call(arrCmdAndArgs)

# Main

def main():
    global blnDone
    global sourceBranch
    global targetBranch
    blnVerbose = False

    # Check if current directory is a git repo
    if (os.path.exists(".git") == False):
        print(".git not found.")
        exit(0)

    # Check for Configfile
    if (os.path.exists(".gitrelease") == False):
        print(".gitrelease not found")
        exit(0)

    config = configparser.ConfigParser()
    config.sections()
    config.read('.gitrelease')
    default = config['DEFAULT']

    strVerbose = default.get('verbose', fallback='false')
    sourceBranch = default.get('source', fallback='develop')
    targetBranch = default.get('target', fallback='master')
    strEditor = default.get('editor', fallback='none')
    strCommand1 = default.get('cmd1', fallback='none')
    strArguments1 = default.get('cmd1_arguments', fallback='none')
    strCommand1FileName = default.get('cmd1_filename', fallback='none')
    strCommand1CommitMessage = default.get('cmd1_commit_message', fallback='')
    strCommand2 = default.get('cmd2', fallback='none')
    strArguments2 = default.get('cmd2_arguments', fallback='none')
    strCommand2FileName = default.get('cmd2_filename', fallback='none')
    strCommand2CommitMessage = default.get('cmd2_commit_message', fallback='')
    strCommand3 = default.get('cmd3', fallback='none')
    strArguments3 = default.get('cmd3_arguments', fallback='none')
    strCommand4 = default.get('cmd4', fallback='none')
    strArguments4 = default.get('cmd4_arguments', fallback='none')

    if (strVerbose.lower() == 'true'):
        blnVerbose = True

    if strCommand1 != 'none':
        if (os.path.exists(strCommand1FileName) == False):
            print("file " + strCommand1FileName + " does not exist")
            exit(0)

    repo = git.Repo(search_parent_directories=True)
    branch = repo.active_branch

    if branch.name == sourceBranch:
        if blnVerbose:
            print(branch.name)
    else:
        print('no ' + sourceBranch + ' branch found')
        exit(0)

    if repo.untracked_files:
        print(sourceBranch + ' branch has untracked files')
        exit(0)

    if repo.is_dirty():
        print(sourceBranch + ' branch has uncommitted files')
        exit(0)

    tags = sorted(repo.tags, key=lambda t: t.commit.committed_datetime)

    strLatestTag = "v0.0.0"
    if len(tags) > 0:
        strLatestTag = str(tags[-1])

    print("Current release: " + strLatestTag)

    strNextRelease = getNextRelease(strLatestTag)

    string = "Give new Release [" + strNextRelease + "]: "
    new_tag = (input(string) or strNextRelease)
    print("new release: " + new_tag)

    # https://git-flow.readthedocs.io/en/latest/releases.html
    #
    # git flow release start v1.4.0 or
    # git checkout -b release/v0.0.5 develop

    strReleaseBranch = "release/" + new_tag
    repo.git.checkout('HEAD', b=strReleaseBranch)

    strArguments1 = strArguments1.replace("{current_release}", strLatestTag)
    strArguments1 = strArguments1.replace("{new_release}", new_tag)

    strArguments2 = strArguments2.replace("{current_release}", strLatestTag)
    strArguments2 = strArguments2.replace("{new_release}", new_tag)

    strArguments3 = strArguments3.replace("{current_release}", strLatestTag)
    strArguments3 = strArguments3.replace("{new_release}", new_tag)

    strArguments4 = strArguments4.replace("{current_release}", strLatestTag)
    strArguments4 = strArguments4.replace("{new_release}", new_tag)

    if blnVerbose:
        print(strCommand1 + " " + strArguments1)

    if strCommand1FileName != 'none':
        # Generate CHANGELOG
        if strCommand1 != 'none':
            runCommand(strCommand1, strArguments1)

        # Manual Change CHANGELOG
        if strEditor != 'none':
            EDITOR = os.environ.get('EDITOR', strEditor)
            f = open(strCommand1FileName, "r")
            call([EDITOR, f.name])

        # git add CHANGELOG
        repo.index.add(strCommand1FileName)
        print("Commit " + strCommand1FileName)

        # git commit -m "docs: update CHANGELOG"
        repo.index.commit(strCommand1CommitMessage)

    if blnVerbose:
        print(strCommand2 + " " + strArguments2)

    if strCommand2FileName != 'none':
        # Generate RELEASE_NOTES
        if strCommand2 != 'none':
            runCommand(strCommand2, strArguments2)

        # Manual Change CHANGELOG
        if strEditor != 'none':
            EDITOR = os.environ.get('EDITOR', strEditor)
            f = open(strCommand2FileName, "r")
            call([EDITOR, f.name])

        # git add CHANGELOG
        repo.index.add(strCommand2FileName)
        print("Commit " + strCommand2FileName)

        # git commit -m "docs: update CHANGELOG"
        repo.index.commit(strCommand2CommitMessage)

    t = threading.Thread(target=animate, args='m')
    t.start()

    # git checkout target
    repo.git.checkout(targetBranch)

    # git merge --no-ff release/v0.0.4 -m "Merge branch 'release/v0.0.4'"
    strMessage= "Merge branch '" + strReleaseBranch + "'"
    repo.git.merge(strReleaseBranch, m=strMessage, no_ff=True)

    # git tag -a v0.0.5 -m v0.0.5
    repo.git.tag(m=new_tag, a=new_tag)

    # git push -u origin target
    repo.git.push(targetBranch, u='origin', tags=True)

    blnDone = True
    time.sleep(0.2)
    blnDone = False
    t = threading.Thread(target=animate, args='d')
    t.start()

    # git checkout develop
    repo.git.checkout(sourceBranch)

    # git merge --no-ff target -m "Merge tag 'v0.0.14' into develop"
    strMessage= "Merge tag '" + new_tag + "' into " + sourceBranch
    repo.git.merge(targetBranch, m=strMessage, no_ff=True)

    # git branch -d release/v0.0.6
    repo.git.branch(d=strReleaseBranch)

    # git push -u origin develop
    repo.git.push(sourceBranch, u='origin', tags=True)

    blnDone = True
    time.sleep(0.2)

    print("Release " + new_tag + " done.")

    if blnVerbose:
        print(strCommand3 + " " + strArguments3)

    runCommand(strCommand3, strArguments3)

    if blnVerbose:
        print(strCommand4 + " " + strArguments4)

    runCommand(strCommand4, strArguments4)

if __name__== "__main__":
   main()
